title: Akanksha Atrey
url: "http://cs.umass.edu/~aatrey"

markdown: kramdown
remote_theme: bk2dcradle.github.io/researcher

tracking_id: #

gem: "github-pages"

sass:
    style: compressed
    sass_dir: _sass
